### ISSUE TITLE
Add support for docker containers

### ISSUE THREAD

**Issue by wrabcak** [containers/udica#1]
```
$ python3 -m udica -i ddbd-c -n ddbd
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tt/g/udica/udica/__main__.py", line 43, in <module>
    main()
  File "/home/tt/g/udica/udica/__main__.py", line 29, in main
    container_caps = parse_cap(container_caps_data)
  File "/home/tt/g/udica/udica/parse.py", line 10, in parse_cap
    return data.split('\n')[1].split(',')
IndexError: list index out of range
```

`ddbd-c` is a docker container, so I'm assuming that udica can't find it and tracebacks

Author: @TomasTomecek

**Comment by TomasTomecek** [comment]
Yes, it wasn't clear to me that this project uses podman only.
